# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0002_auto_20170410_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('apellidoPaterno', models.TextField(max_length=100)),
                ('apellidoMaterno', models.TextField(max_length=100)),
                ('fechaCreacionRegistro', models.DateField(default=django.utils.timezone.now)),
                ('formaContacto', models.CharField(choices=[(b'per', b'Personal'), (b'tel', b'Telefono'), (b'ema', b'Correo electronico'), (b'otr', b'Otro')], default=b'rec', max_length=3)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=13)),
                ('medioContacto', models.CharField(choices=[(b'rec', b'Recomendacion'), (b'ins', b'Instalaciones'), (b'int', b'Internet'), (b'lon', b'Lona publiciataria'), (b'vol', b'volante'), (b'rad', b'Radio'), (b'otr', b'Otro')], default=b'rec', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[(b'col', b'Colbach'), (b'sec', b'Secundaria'), (b'cen', b'Ceneval'), (b'pre', b'Prepa abierta'), (b'prp', b'Propedeutico prepa'), (b'pru', b'Propedeutico Uni'), (b'otr', b'Otro')], default=b'col', max_length=3)),
                ('duracion', models.CharField(choices=[(b'dos', b'Dos meses'), (b'cua', b'Cuatro meses'), (b'och', b'Ocho meses'), (b'otr', b'Otro')], default=b'col', max_length=3)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('clasificacion', models.CharField(choices=[(b'glo', b'Global'), (b'are', b'Area'), (b'otr', b'Otro')], default=b'glo', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRegistro', models.IntegerField()),
                ('concepto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateField()),
                ('factura', models.BooleanField()),
                ('montoCubierto', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('apellidoPaterno', models.TextField(max_length=100)),
                ('apellidoMaterno', models.TextField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('puesto', models.CharField(max_length=50)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudadEstado', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('telefonoExtension', models.CharField(max_length=50)),
                ('contactoEmpresarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.ContactoEmpresarial')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('horarioBaseInicio', models.TimeField()),
                ('horarioBaseFin', models.TimeField()),
                ('rolHorarioInicio', models.TimeField()),
                ('rolHorarioFin', models.TimeField()),
                ('diasClase', models.CharField(choices=[(b'lav', b'Lunes a viernes'), (b'lmv', b'Lunes, miercoles y viernes'), (b'syd', b'Sabado y domingo'), (b'sab', b'Sabado'), (b'dom', b'Domingo'), (b'otr', b'Otro')], default=b'lav', max_length=3)),
                ('clasificacion', models.CharField(choices=[(b'reg', b'Regular'), (b'rec', b'Recursamiento'), (b'otr', b'Otro')], default=b'glo', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema', models.CharField(choices=[(b'col', b'Semanal'), (b'sec', b'Quincenal'), (b'cen', b'Mensual'), (b'pre', b'Un solo pago'), (b'otr', b'otro')], default=b'sem', max_length=3)),
                ('fechaInicio', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudadEstado', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudadEstado', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('telefonoExtension', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='centroInscripcion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='colegiatura',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='perteneceEmpresa',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='status',
        ),
        migrations.AddField(
            model_name='alumno',
            name='calle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='colonia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='cp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='documentacionCompleta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='entreCalles',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estadoCivil',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='gradoEstudios',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='numeroHijos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fechaCreacionRegistro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numeroControl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Alumno'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='plantel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Proovedor'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='plantel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Empleado'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='servicioInteres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Servicio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Empresa'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='idAspirante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Aspirante'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='plantelRegistro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel'),
        ),
    ]
