# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0004_auto_20170420_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='servicioInteres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Curso'),
        ),
    ]
