# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0005_auto_20170420_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='apellidoMaterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='apellidoPaterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidoMaterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidoPaterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='plantel',
            name='ciudadEstado',
            field=models.CharField(max_length=50),
        ),
    ]
