# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0006_auto_20170421_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='idAspirante',
            new_name='Aspirante',
        ),
    ]
