# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('aspirante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotoria.Aspirantes')),
            ],
        ),
    ]
