# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirantes',
            name='servicioInteres',
            field=models.CharField(choices=[('Recomendacion', 'Recomendacion'), ('Instalaciones', 'Instalaciones'), ('Internet', 'Internet'), ('Lona publicitaria', 'Lona publiciataria'), ('Volante', 'volante'), ('Radio', 'Radio'), ('Otro', 'Otro')], default='Colbach', max_length=20),
        ),
    ]
