# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0009_auto_20170525_1040'),
        ('promotoria', '0002_auto_20170610_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacionRegistro', models.DateField(default=django.utils.timezone.now)),
                ('numeroControl', models.IntegerField(null=True)),
                ('curp', models.CharField(max_length=20, null=True)),
                ('calle', models.CharField(max_length=100, null=True)),
                ('colonia', models.CharField(max_length=100, null=True)),
                ('entreCalles', models.CharField(max_length=100, null=True)),
                ('cp', models.CharField(max_length=5, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('gradoEstudios', models.CharField(max_length=50, null=True)),
                ('estadoCivil', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('numeroHijos', models.IntegerField(null=True)),
                ('documentacionCompleta', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aspirantes',
            options={'ordering': ['apellidoPaterno'], 'verbose_name_plural': 'Prospectos'},
        ),
        migrations.AlterField(
            model_name='aspirantes',
            name='servicioInteres',
            field=models.CharField(choices=[('Secundaria', 'Secundaria'), ('Preparatoria Abierta', 'Preparatoria Abierta'), ('Colbach', 'Colbach'), ('Ceneval', 'Ceneval'), ('Propedeutico', 'Propedeutico'), ('Otro', 'Otro')], default='Colbach', max_length=20),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Aspirante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotoria.Aspirantes'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Empresa'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='plantelRegistro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel'),
        ),
    ]
