# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 03:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siad', '0001_initial'),
        ('promotoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_materia_1', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_2', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_3', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_4', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_5', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_6', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_7', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_8', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_9', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
                ('calificacion_materia_10', models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Colbach', 'Colbach'), ('Secundaria', 'Secundaria'), ('Ceneval', 'Ceneval'), ('Prepa abierta', 'Prepa abierta'), ('Propedeutico prepa', 'Propedeutico prepa'), ('Propedeutico Uni', 'Propedeutico Uni'), ('Otro', 'Otro')], default='Colbach', max_length=25)),
                ('duracion', models.CharField(choices=[('Dos meses', 'Dos meses'), ('Cuatro meses', 'Cuatro meses'), ('Ocho meses', 'Ocho meses'), ('Otro', 'Otro')], default='Dos meses', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('clasificacion', models.CharField(choices=[('Global', 'Global'), ('Area', 'Area'), ('Otro', 'Otro')], default='Global', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentacion_completa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Documentacion',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_registro', models.DateField(default=django.utils.timezone.now)),
                ('numero_de_control', models.IntegerField(null=True)),
                ('curp', models.CharField(max_length=20, null=True)),
                ('calle', models.CharField(max_length=100, null=True)),
                ('colonia', models.CharField(max_length=100, null=True)),
                ('entre_calles', models.CharField(max_length=100, null=True)),
                ('cp', models.CharField(max_length=5, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('grad_estudios', models.CharField(max_length=50, null=True)),
                ('estado_civil', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('numero_de_hijos', models.IntegerField(null=True)),
                ('servicio_interes', models.CharField(choices=[('Secundaria', 'Secundaria'), ('Preparatoria Abierta', 'Preparatoria Abierta'), ('Colbach', 'Colbach'), ('Ceneval', 'Ceneval'), ('Propedeutico', 'Propedeutico'), ('Otro', 'Otro')], default='Colbach', max_length=20)),
                ('adeudo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Aspirante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotoria.Aspirantes')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Empresa')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(to='controlescolar.Materia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='plantel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='documentacion_entregada',
            field=models.ManyToManyField(to='siad.Documento'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante'),
        ),
    ]
