# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Colbach', 'Colbach'), ('Secundaria', 'Secundaria'), ('Ceneval', 'Ceneval'), ('Prepa abierta', 'Prepa abierta'), ('Propedeutico prepa', 'Propedeutico prepa'), ('Propedeutico Uni', 'Propedeutico Uni'), ('Otro', 'Otro')], default='Colbach', max_length=25)),
                ('duracion', models.CharField(choices=[('Dos meses', 'Dos meses'), ('Cuatro meses', 'Cuatro meses'), ('Ocho meses', 'Ocho meses'), ('Otro', 'Otro')], default='Dos meses', max_length=15)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('clasificacion', models.CharField(choices=[('Global', 'Global'), ('Area', 'Area'), ('Otro', 'Otro')], default='Global', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('horarioBaseInicio', models.TimeField()),
                ('horarioBaseFin', models.TimeField()),
                ('rolHorarioInicio', models.TimeField()),
                ('rolHorarioFin', models.TimeField()),
                ('diasClase', models.CharField(choices=[('Lunes a viernes', 'Lunes a viernes'), ('Lunes miercoles y viernes', 'Lunes, miercoles y viernes'), ('Sabado y domingo', 'Sabado y domingo'), ('sabado', 'Sabado'), ('Domingo', 'Domingo'), ('Otro', 'Otro')], default='Lunes a viernes', max_length=30)),
                ('clasificacion', models.CharField(choices=[('Regular', 'Regular'), ('Recursamiento', 'Recursamiento'), ('Otro', 'Otro')], default='Regular', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
