# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0002_curso_materia_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='horarioBaseFin',
            new_name='horarioFin',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='horarioBaseInicio',
            new_name='horarioInicio',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='rolHorarioFin',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='rolHorarioInicio',
        ),
        migrations.AlterField(
            model_name='materia',
            name='diasClase',
            field=models.CharField(choices=[('Lunes a viernes', 'Lunes a viernes'), ('Sabado y domingo', 'Sabado y domingo'), ('Solo sabado', 'Solo sabado'), ('Solo domingo', 'Solo domingo'), ('Otro', 'Otro')], default='Lunes a viernes', max_length=30),
        ),
    ]
