# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0003_auto_20170614_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='diasClase',
        ),
    ]
