# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0004_remove_materia_diasclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='adeudo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
