# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 02:45
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0005_estudiante_adeudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_10',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_3',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_4',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_5',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_6',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_7',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_8',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='calificacion_materia_9',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_1',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_10',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_2',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_3',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_4',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_5',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_6',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_7',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_8',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia_9',
            field=models.CharField(default='Nunguna', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numero_reprobadas',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='promedio',
            field=models.DecimalField(decimal_places=2, default=Decimal('-1.0'), max_digits=4),
        ),
    ]
